spring:
  datasource: 
    driverClassName: com.mysql.cj.jdbc.Driver    
  jpa: 
    hibernate :
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  sleuth:
    sammpler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411/              
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka  
