server:
  port: 8100
spring: 
  application: 
    name: CallDetailsMS
  datasource: 
    url: jdbc:mysql://localhost/infytel-calldetails
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka
    
