spring: 
  application: 
    name: CustomerMS
  datasource: 
    url: jdbc:mysql://localhost/infytel-customer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka    
friend:
  uri: http://localhost:8301/customers
path:
  uri: http://localhost:8400/path
