spring: 
  application: 
    name: CustomerMS
  datasource: 
    url: jdbc:mysql://localhost/infytel-customer
management: 
  security: 
    enabled: false    
friend:
  uri: http://localhost:8301/customers
path:
  uri: http://localhost:8400/path
