spring: 
  application: 
    name: CustomerMS
  datasource: 
    url: jdbc:mysql://localhost/infytel-customer
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 10
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 10000
      metrics:
        rollingStats:
          timeInMilliseconds: 10000            
